### ISSUE TITLE
Crossbow report has started failing due to not being able to set renv

### ISSUE THREAD

**Issue by raulcd** [ursacomputing/crossbow#83]
The crossbow report generation seems to be failing with:
```
The downloaded source packages are in
	‘/tmp/RtmpQmd3yI/downloaded_packages’
Run cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
Error in heredoc("\n      renv %1$s was loaded from project library, but this project is configured to use renv %2$s.\n      - Use `renv::record(\"%3$s\")` to record renv %1$s in the lockfile.\n      - Use `renv::restore(packages = \"renv\")` to install renv %2$s into the project library.\n    ") : 
  could not find function "heredoc"
Calls: source ... renv_bootstrap_load -> renv_bootstrap_validate_version
```

See: https://github.com/ursacomputing/crossbow/actions/runs/8642504449/job/23703036423

**Comment by raulcd** [comment]
@assignUser @boshek  any idea?

**Comment by boshek** [comment]
I believe this is a bug in [renv](https://github.com/rstudio/renv/issues/1874) so it will need to fixed over there.

**Comment by assignUser** [comment]
Hm, can we not downgrade and pin renv or something?  Hm, setup-renv does that... ugh

**Comment by assignUser** [comment]
Though @boshek looking at this https://github.com/r-lib/actions/blob/v2-branch/setup-renv/action.yaml#L27 we should be able to install another version before that step and that should not be installed over?

**Comment by boshek** [comment]
Yup that makes sense. Looks like we've been just lucky up to this point as we haven't been installing the renv specified in the lock file: https://github.com/ursacomputing/crossbow/actions/runs/8633141771/job/23665471347#step:9:91

**Comment by boshek** [comment]
This _should_ just work again as renv fixed this upstream. Will monitor though.

**Comment by raulcd** [comment]
The last job execution was successful. I am closing this!
